### PR TITLE
[lensesio/exceptions] raise exceptions rather exiting

### PR DESCRIPTION
**Pull request by ulfox**
Issue: Lenses is a module and hence should raise exceptions rather exiting and causing the whole application to exit

Reporter: https://github.com/lensesio/lenses-python/issues/56
Fix: switch all lines of lensesio.lenses.main from print&exit to raise lenses_exception(e)

### CODE REVIEW

**Comment by ulfox** [comment]
@andmarios fix for issue raised by https://github.com/lensesio/lenses-python/issues/56

**Comment by ulfox** [comment]
The tests can not run because the license needs to be updated. Will check to update the test with the none license version of Lenses 4

**Comment by montsamu** [comment]
Can we get this to merge and (finally!) publish a new lensesio version to pip?

**Comment by ulfox** [comment]
@andmarios ^

**Pull request merged**
